server:
  port: 8082

spring:
  application:
    name: authorservices

  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      show-sql: true

  management:
    tracing:
      sampling:
        probability: 1.0
