server:
  port: 8081

spring:
  application:
    name: bookservices

  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    dialect: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  management:
    tracing:
      sampling:
        probability: 1.0
